# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XS026qqNsuzRbiv-mdA9f9El-43eIYBq
"""

import streamlit as st
import numpy as np
import onnxruntime as ort
@st.cache_resource
def load_model():
  return ort.InferenceSession('diabetes.onnx')


session = load_model()
st.title("Decision Tree ONNX Model")

st.write("Enter the values")
input_str = st.text_input("Example")
if st.button("Predict"):
  try:
    input_array = np.array([list(map(float , input_str .strip().split(',')))], dtype = np.float32)
    input_name = session.get_inputs()[0].name
    ort_inputs = {input_name:input_array}
    pread  = session.run(None , ort_inputs)[0]
    st.write(pread)
  except Exception as e:
    st.write(e)













































